#! /bin/bash
## Install docker
sudo apt install docker.io
## grant docker permission to ubuntu user
sudo usermod -a -G docker ubuntu
sudo docker run -d --name sonar -p 9000:9000 sonarqube:lts-community
## Logout and back in to cycle changes or run docker as ubuntu user
exec bash
